export {default as Login} from './Login'
export {default as Register} from './Register'
export {default as Home} from './Home'
export {default as Paiement} from './Paiement'
export {default as Order} from './Order'
export {default as Menu} from './Menu'
export {default as Profile} from './Profile'
export {default as Favorites} from './Favorites'